<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="../css/common.css">
<title>Insert title here</title>
</head>
<body>
商品ページ
<table align="center" class="listTable">
	<tr>
		<th>商品名</th>
		<th>値段</th>
		<th>分類</th>
		<th>養蜂家</th>
		<th>地域</th>
		<th>花の名前</th>
		<th>味の違い</th>
		<th>画像</th>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
	<tr>
		<td>おいしいはちみつ</td>
		<td>1,250円</td>
		<td>百花蜜</td>
		<td>ジョン・レノン</td>
		<td>イギリス</td>
		<td>いろんな花</td>
		<td>ジョンな味</td>
		<td></td>
	</tr>
</table>

</body>
</html>